### ISSUE TITLE
Checklist for v1.4 release

### ISSUE THREAD

**Issue by mr-c** [ged-lab/khmer#906]
- [x] Screed v0.8 release

Finish these PRs:

- [x] check for errors while writing to disk #856
- [x] Option for printing diginorm output to stdout #882
- [x] add thread safety to CountingHash::abundance_distribtion #900
- [x] catch more exceptions & make a couple tests more robust #889
- [x] quiet OSX build #887

**Comment by mr-c** [comment]
- [ ] preliminary coverity scan
- [ ] preliminary release checklist

**Comment by mr-c** [comment]
- [ ] add release notes #807

**Comment by mr-c** [comment]
- [ ] acceptance tests
- [ ] batlab
- [ ] freshen release notes

**Comment by mr-c** [comment]
rc2 has been cut. Release checklist is done through step 9.
BaTLab testing is underway http://submit-1.batlab.org/nmi/results/details?runID=319323

**Comment by mr-c** [comment]
BaTLab success except for a bug of theirs

**Comment by mr-c** [comment]
Coverity scan passed: https://scan.coverity.com/projects/621

**Comment by mr-c** [comment]
Running acceptance tests via Docker (!) on Athyra.

**Comment by mr-c** [comment]
Acceptance tests passed.

**Comment by mr-c** [comment]
Release notes updated https://github.com/ged-lab/khmer/releases/edit/untagged-a7c5873fb5c7f8ff6814

**Comment by mr-c** [comment]
Done!
